name = "math"
version = "0.1.0"
defaultTargets = ["math"]

[[lean_lib]]
name = "Math"

[[lean_exe]]
name = "math"
root = "Main"

[package]
name = "math"
version = "0.1"
leanVersion = "leanprover/lean4:v4.20.0-rc2"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.11.0"