
-- The Genetic Codeclick to expand

-- Problem

-- The 20 commonly occurring amino acids are abbreviated by using
-- 20 letters from the English alphabet (all letters except for B, J, O, U, X, and Z).
-- Protein strings are constructed from these 20 symbols. Henceforth, the term genetic
-- string will incorporate protein strings along with DNA strings and RNA strings.

-- The RNA codon table dictates the details regarding the encoding of specific codons into the amino acid alphabet.

-- Given: An RNA string s

-- corresponding to a strand of mRNA (of length at most 10 kbp).

-- Return: The protein string encoded by s

-- .
-- Sample Dataset

-- AUGGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA

-- Sample Output

-- MAMAPRTEINSTRING


def parse3AAS (aas : Char × Char × Char) : Option Char :=
  match aas with
  | ('U', 'U', 'U') => some 'F'
  | ('C', 'U', 'U') => some 'L'
  | ('A', 'U', 'U') => some 'I'
  | ('G', 'U', 'U') => some 'V'
  | ('U', 'U', 'C') => some 'F'
  | ('C', 'U', 'C') => some 'L'
  | ('A', 'U', 'C') => some 'I'
  | ('G', 'U', 'C') => some 'V'
  | ('U', 'U', 'A') => some 'L'
  | ('C', 'U', 'A') => some 'L'
  | ('A', 'U', 'A') => some 'I'
  | ('G', 'U', 'A') => some 'V'
  | ('U', 'U', 'G') => some 'L'
  | ('C', 'U', 'G') => some 'L'
  | ('A', 'U', 'G') => some 'M'
  | ('G', 'U', 'G') => some 'V'
  | ('U', 'C', 'U') => some 'S'
  | ('C', 'C', 'U') => some 'P'
  | ('A', 'C', 'U') => some 'T'
  | ('G', 'C', 'U') => some 'A'
  | ('U', 'C', 'C') => some 'S'
  | ('C', 'C', 'C') => some 'P'
  | ('A', 'C', 'C') => some 'T'
  | ('G', 'C', 'C') => some 'A'
  | ('U', 'C', 'A') => some 'S'
  | ('C', 'C', 'A') => some 'P'
  | ('A', 'C', 'A') => some 'T'
  | ('G', 'C', 'A') => some 'A'
  | ('U', 'C', 'G') => some 'S'
  | ('C', 'C', 'G') => some 'P'
  | ('A', 'C', 'G') => some 'T'
  | ('G', 'C', 'G') => some 'A'
  | ('U', 'A', 'U') => some 'Y'
  | ('C', 'A', 'U') => some 'H'
  | ('A', 'A', 'U') => some 'N'
  | ('G', 'A', 'U') => some 'D'
  | ('U', 'A', 'C') => some 'Y'
  | ('C', 'A', 'C') => some 'H'
  | ('A', 'A', 'C') => some 'N'
  | ('G', 'A', 'C') => some 'D'
  | ('U', 'A', 'A') => none
  | ('C', 'A', 'A') => some 'Q'
  | ('A', 'A', 'A') => some 'K'
  | ('G', 'A', 'A') => some 'E'
  | ('U', 'A', 'G') => none
  | ('C', 'A', 'G') => some 'Q'
  | ('A', 'A', 'G') => some 'K'
  | ('G', 'A', 'G') => some 'E'
  | ('U', 'G', 'U') => some 'C'
  | ('C', 'G', 'U') => some 'R'
  | ('A', 'G', 'U') => some 'S'
  | ('G', 'G', 'U') => some 'G'
  | ('U', 'G', 'C') => some 'C'
  | ('C', 'G', 'C') => some 'R'
  | ('A', 'G', 'C') => some 'S'
  | ('G', 'G', 'C') => some 'G'
  | ('U', 'G', 'A') => none
  | ('C', 'G', 'A') => some 'R'
  | ('A', 'G', 'A') => some 'R'
  | ('G', 'G', 'A') => some 'G'
  | ('U', 'G', 'G') => some 'W'
  | ('C', 'G', 'G') => some 'R'
  | ('A', 'G', 'G') => some 'R'
  | ('G', 'G', 'G') => some 'G'
  | _               => none


-- def teste (str : String) : Int :=
--   match str with
--   | C => 1

-- TODO: termination
partial def problem (str : String) : Option (String) :=
  match str.data with
  | a :: b :: c :: xs =>
    let abr? := parse3AAS (a, b, c)
    match abr? with
    | some abr => do return String.mk (abr :: (← problem ⟨xs⟩).toList)
    | none => do return (← problem ⟨xs⟩)
  | _  => some ""


def solution := problem

-- Sample Dataset

#eval "AUGGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA"

-- AUGGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA

-- Sample Output

/- #eval problem "AUGGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA".toList -/
#eval (solution "AUGGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA").get!
/- #eval problem "AUGGCC".toList -/
/- #eval problem "AUG".toList -/
#eval solution "AUGGUUGCACUUCUUAUGGAUUCAAAAGAGGUUGAGAGACACAACGCUGUGGAUACUGAGAGGCCGUUUGUGACCGGCUCUCUAUUAUUCCUCCUUACGAGAGACAUAGACCAUGCCGCUAGGUCCGGCGUAAACCGAUCUGCUGCCUUUUCCUCCUCCUGUUUAGUUAUAGCAACACAACGUGUAGACUACUUUUCUGCCGUUAUGUGGAUGGAUGGCGCUGAAGUCUACACCCCGGCGCAUUCCCCUUCGAUUUCAGCAGCCCAACGAUAUUGCUGGAACGCGGAUGUAUACUUCGAUGUAAGUUGUUUGACAAGUUCUUCAUAUAUUGCGAGACCGGGAGCACUGUCCCUACUGAGGGGCUCGAAAGUUCUUAGAGACAAAGCGUCAGGUUUGUUUAGGACUUCGUCAGACUUGGAAUGUUAUUCACGUCGACCUCCCUCGGAGCUCACGGCAAAUCUGUUACGCGGGAAUCGAACCCGUUACCGUCCGCCUCGCAAAAAGGCAAGCCCGCGCCCAGUGCAUAACCCGGGCGUUCUAACCUGUCCGACCCCGAGGCUCCGAUACGUGCAUCUCAGUGCAAACCUCACUCCGAGGACCAGUUCCUUGUUAGAACGAAGCACCGGCGGCGGCGUCACUCACGCCCUCUCGGCGUGCAGGCUCAACGCACGCACUAUAUACGGUCCCUUGCGAAUUCUCGGCUAUUUCCGAUGGAAGACACAGUACGCGACAAUUGGGAAUUACCUCAAAGACGUUACCAUCUUUCGUAAAUUUUCUGUCUGUGCUACGACUUAUGUGCUGGGUCCAGGUCCAUAUAUGUCUGCCGUUGACAUUGAAGCUCGACGUUCCAGCACUAUUUGUGGUCCUAUUGCAUCAUUGGACAGGCGCGGUCCUGCAAGCCACCAUAGUCGGCCGCUUUUGUUUCUACUUGCGAGCUACAUCAGCGCGACGAUUUCCACUCUGGUGUUGGUCCGAAACGUGGAUCACUCCAGGAGCAAGGCAUAUCUUCUCUUGACCAAAACCGCGUGUAUUCAUCGCGUGUGUUUCGCGAUCAGAGCCUUAGAGACGUCAUCCCGAAGGCCGUGCAAUCGCCCCGGUAUACAUAUACGGGGUGCUACACGCUCGGGAUCAUGUCAUGACAGUUCCAGCACUCUUCACGCCACCCAUAGCUCGACUGCAAAUUUUGAGGAUUGCGGAGUGGCGGUGUUAUCUCGCCGACGCACCGUUUCCUGCCUCAACCCCACCGGUUGCUUGAGCGGAAAUAAGAUAGUAGGGGCUAUAGAUAGACCUUUUUUUGCAACACAGUCGUUGAAGGUCGACGGCCAAAGGGGACACCAGGUCGGGCCACUUCAAUGGCUUCCUUAUUCGACUCAGGCAAAUGAGCUACCGAUGGAAACUACGACGCCGAGUCUAUUCCGUAAGCAUUGGGUAUCGCGACCUCACCAUACUGGCGCCCUUCUCGUCGGACUAUCACUUGUCUCUGAAGUACACCUAGUUUGUAGAGAGGCAAGUAGUGACCAUACGAGGCUACGCUACAAGCCCGUAGGCGGUGCACCAGCUUUGGGUUGGAGCAGCUAUGCUGUGAGUCGUGGGGUUGUGUUCGCGGAGGCAAGCGUAACUAUUUCAACGAAAUGGGCGCCUAAAUAUGCUUCAAGAGGAGUAAUUGCCCUGCUCUCUGGUAUCCCAGGAGGCAAACAUCCAGCACGGAACGUCUUCUCUUGCCAUGCAGACUCGAGCGUUCACAAUAGAGGUGCUGUUGACCAGGUUCCUACCUUUAAAACCAAUAUACAUUUUGUGCGUUGGACCGCUAAAAGUCAGAGACUCGCUUUAAGCAGGCCUCCGGAAUUCAGACCUCCCUCACAGCCGGGUCGGUCAAGAAGCCAUGGGCUACCUUCUAGUACACUGAUCAGUACAUUUCCCGCCGGACCAUUUCGGGUGCAACAAGCGACGACCGUUAGCUCGACCAUAGGCCCCAGGAUCAAGGCAAGUCAACAGUUAAGCCUUCACAGGUGCAUUCGGGUUAUAGACCAUUCCGAGAGCUUUUCCUACGGGUAUUACAAGCAGUUCUGUUAUCAUAUGCGCACCGUCGGACCGCUUGUUCACAUAAGCGGGGCACAGCCUCCGCACUCACGUAAGCGAGUCCGCAAGCCUCCACGCUGUUCAGUACUGCGGUUGUCAUUCUGCGGAAAUGGUCGUUCAAAACUGAAGCUCGUAGGCAACGAAUGCGCUACCCAGUCAGUAGGCAUGGGAAACUCGUGUCCACGCUCUCCUAACAGCACAUCAAUUGCAACUGGACAGCCUCCUCAACACAUACUGAGACCCGGAGUCGCUUACAGACGCAGCGCGUCUGAUAAGACGUUCCCGAGGUCAGCACCGUCUAUGCUGUGCGGUUUAACAAGCCAUUCGGGCGGAGUUGCAAGCUUGCCGGGUCCAUCUAUGGUCAACUUAGGGUCUAUAAUGUUUUGGACUGGAGGCGCGGACAACAGAUACCGCCGCAUCAGUUACACCAGUGGGCUGACUAAACCGAGCAUGUCCUGCGUAGUCGGAUGCCGGAUUGUGAUAUACUGCACUGGCAAAUUUAAGGUGCGACAGCAGCUGCAAACCACGUGGAGUGUAUCGCGUACAAAAUCAUCCAGGUGCUCGACAGUGAUGCUUUCAUCUUACUCGCUUCACGACCAGAGGUUUGUCGUUUUCGCAAAUGGGCUUAGGAGGGAUUUUCACAAGUAUUCGCGCGUGUUUGUCGCAUGGGCAUGGCGCACCAUACCAGUCAUAAUACAAAAAGACUACGGUCCGGCCCAGCUACGAGCGGUCAUAUUGUCAUACGUGUCAAGGGCUCACAGUAUCGAUGAGUUCCCGAUAUGCUUAAAGUCUGCUACUUAUCCCUAUUCUUGUUUCACAAUUAUAAUCUAUCCCCAGCUUCUAGAAGAGUGGAACUUUACCCUCCCAGAACAGCCGCUGUCCGGUCGGAGCUCGCCCAAAACAACGAGCGCCUUGGUAGGAUCAGGCAGCCUUACAGUACUUGACCCCGAAGAACUAGCCUCCGAUUCCCGCCCCCCCUUGAGGCCUGGAACCUUGCCACGAGAGUGGAAGCGGCCCCGUGCUCCACAAAAAAAUGUUCUUGUAGACUCCAUACUAAAGCAAGCGACCGUUAUGAUGGCCGAGCGCGGCCGCGUCCUCGUUUUAUAUUCCAAUCGCCUUCGUCGUAUCAUAAAAAUCAUCCCCGUCCUUUUCUGGAAUGUCCCCAGUAGAAUAAACGCGUCAACGAGACGCCACGUAUCGUACCCUCAACUAGGCAUGGACAUUUAUUCAUCGCAUCGCAGGCGCCAUCUAAAAUCUAGCAAGCUGAUCUUUAUCUCGAGCGGAAGUGAGUCCCAGAAUAAUUGGUGCCCCCGCGCCCAUAGUAUGAAGUACGGCACCCGAAUUCUGGUUAGUGCUGAGGUGACUUCAACACUUUCGUUGUCAACUGCAAUUACUUACGGCUCGACACUCGUGUCACACCCGGCGGUGAACUAUCCGUCAGCUUGGCAGUGCGCGCUUACGACUCUACUUACAACCGACAAACCCCGGUACCACCCUCAUGGUAAUAACAGGGCACUAGGUCUUUUCAUGCGACCAUUCACGAAUCCAUUUGGGGGGUUGGACAUAUACUCCAGGGUUAGAUCAACCGCCCAGUGUGUGAAUAGCCGGGUAUGUCACGCCCACUUCAAGCGUAGGAGUCUAGUAGCGCAGCAGAACUCUGAUAGGACAGAAAAGACUAAUUUGGUGCCAUCAAACCGGGACCUAGCGAGAAAGACAGUCGACGGUUCCGAGUUUGAGGUAGUACGCAGAUCUAGCGGGAGGAGGCGAAGCACUGAAGCCCUAACAAGACACGCGAGAGAGUUCCUUGAGAAUUUAUUGCGCCCGCAGGCGAUUUAUCUAUCGUGGGAAAUCUUGCAGUAUAACACGUGGCCGCGCUUAAGCUGCACGGGAACUGCGGUGUGCUUACGUCGGGGGGUGCCACACCAGGUCCGGAUAACUUUAAAUUAUUUGACGGUGCUCGGUACACGUUGGUAUAAGAAACGCCAAAAAGUGUCCCGUAUGGAUCCCAAUCUGGCGAUAUCACCUACUUUGUUAAGCGGGCGACGGGGUAAUCGGGUCGCCUCGCGUCCAGAUUGCUACUUGUCCCCCACGCGAAACGCACCUGCGCGGAAUGGAGCCAACCAAGGCACCUCCCGUCCAGGUGGGAUUUACGCCGACCCCCGAGGGACGACAUUAAGCGCUCUAGGGCCAGUGACGGUAAGCUGGGACUCGGGGAAGAAUAUGGUACGUCUGGAUGUAGUGGGAUUGACCCCGAUGGUUCCAAGAGAUUUGAGUAGCGUGCGUAUUGUUUGGACUCGUGCGAUUCGGGACAUUUGCUCCGUACUUGUCCGUAGUAGGGCGGCUGUAUCUCAGGGUAGACAAGAUAUAGCCAAGUGUGGUCACCACCUUAUCACACGGAGAAUAGAGCAGUGGAAUCGCAACUUGCGCGGUAAAAUAUCCGCUAACACCCUGUCUGACUCUGUCGCUAGCAGUUGGGGCAUUAAUUCCGCCGACUUCCCAGCGUGCAGAUGUGCUAAUUCCAGUUCGCAAACCCCCGGACAUAACGGCACUUCCCCACUCUUAAUGUGGACAAUAGCUCAGGGUGGACGGGUCCGUAGUGCUUAUAUUGCGGUAUCGAUUCGACGGCCAUCCUUCGGGACGGUCUCCGCGGUACUUUUAAGCCUGCAGUCGUUUCCAGACUGUUCGCCUUGUGUCCGUCGGGCAGCAGACUCGAAUAUGUAUUACAUCCUCAUAGGGCUCCUCGAGCCUGGUUGCCAAAGAUCUGCAUGCGAACUCCAAAGUUCUAAUCAAAUUCGCUGCCUCUGCACCGGCGGAGUCGGCAUUAGUCAGACCCUGCCCGUGCCGUGCCGUGCCACCAACCGGUAUCUGGCUAAUUAUGCCGCCAUGCAGAUAACGUUCUAUGGCCAUCAUCGUUCCAGCUAUAUCUCUCGCCGCGGUGUAACCGGGUUUACGGGUGAAGCUCCUACAAGUGUAAUCAUACACGUUUUCCCAAUGGAUGAAAAUUCAGCCGCUGUCCAUAGGGGGGAUUACGCUACGACUGACUUUCGUUGUCCGCCGCAUGAUAGAUUAGCGAUCGUAACCAAACAUACACAUACAGUGUGGCUUGCCGGGUGCAUCUAUGCAGUCUUGAUAAAGGGGCAUGCAAAAAGUGCUGAGUUGCCUGUUUGGAAUGCUAAUGGCGAACCACCUGCCCACCCAGGCAUUAUUAACAGUAAUUGCAUCGAUGGAUUCCCGGGGUUCGCUCUUGAGCGGCUUGCUGCCCGGCACAGGUCCACACCCGGGAUACGCUUUUGCACCCAGCAAAUAUGGCUAAAUAAGUCGAGAUUUUUUACCCUCCUGCUGGACAGGUCGAGAGCCAUAGGCACGGUACACAGUAAGGGGUCGCUAAAGCAUAAUUCUGGACUUUCGUUAUCAUGGCUAGGCGUCCACGAAUGGUGGAGCACAGCAAGAGAUCUCCAUCAUUGGACGAGUAGGUUCAUACAUCUAUGUUCUUCACCAUGGAAUCAAACCGGAAGCCGAGGCGUUGGAUGCAACACAAAUCCGGAAUUUUUCGAAAACCCAUCCGAAAGCGCGCCCAUACUCGGCCACAGGGAUGUGCUGAAUUUUUUCUUACGACCCGAUAUUCGAUCACAAACGAAUCUAAGCCUCAAAGCGAUUCGGCCUCACGACCUGGUCGGUCAAUGCGAACUGUUCGAACUUCGGACGCGAGCGCACGUGACCGCAUACGUGAUGAACCGACAUGAGGUUUUAGGGUCCGAGGGGGGCUCGACACUCCCAGAGAAAACAGGGUCGUGUAACCGAGGAGAGGUUUACUGGACAAUGGCUGUUCGAAACGUUCAUAACUUCGGUGCUAUGGAGCGACAGGUGUUCCGCAAACUGAGCUCACGGCACAGCUUCCCAAUACUGGCUUAUUUGACGCCCACAUUCGCGCAUAUAGCAGCGGCGUGGCGCUUAGUGCCCGAUAAACGGUCGAGGUUUUGUUGGAACGGAGCAUUGUUCCAAGAGUAUACGCAAGCAACGGUAUCGGUCUUAUGCAAACCAGAUGGAUGUAGUAAUAUAUCGGCAAAACUUCUACAGGUGUCGGCGAGGCGAAUAUUAACGGCCUGCAUCCAUCAGUCUAGAAAAGAGAGGGUUUCUACGUACUUAGAUGUCGCCUGCACAGUACCGACGAGUUGGCUUAGGGUCCUGUCCGAGUUUGUUCACAUAGUACCGAGAGGCUUAAGGCAGAGCGUCAGGUCUGAUCCCAAUGCUCGUACCUCCGUGGAUGUAUGGAUUUGGGAGCGCCAAAAUACUGUGCUUGACCCUCUCGUUAAAACGGUGGAGCUGUCCAAGAUUAUGAACGCCACACCAAGAAUCUCACCGUGUCGCAAUACGCGCCCCGCGACCAUUUUAUAUUCACCAUCCAUAACUACCACGAUUCAUUUUGAGCUAUGCAAGACCCGUACCAAGCACUCCUCGACUACCGGGAUUAUCGGUCCGCAGACGUCUUACACCGUUUUGAAUGAUAUACGCUUAGGACGGGGGGUCUGGUCAGCAGGAAACCUUCAUGUAGCAGUACCCUGUAAAAUCGACAGUAGAGUCAAACAUGACGAUUAUAGCAUAAACCAGAGACAGAACGACUUCGAGUUGGUGACGUGUCUACUAUGUAGGCCGGUCAAGAUUUCAAAGUGUCGCGCGCAUCCAUGCUCCGCUAGAAGACCUAUAAGGCAAGGCGUGUCGAUUUACUCGUCCUGCAUUCCAACCCACUCCCUCCCGUGUAUUCGUAGCGCUCACAUGUCUACCCUUGCCCAGUAUGCUUUUGCGCAUCGGGCAGGCUCAACAAUCAUAGCACGCCUGGCAUAUUUUCAAAUACCAAUCUGGCCGAAGCUGCAGGGCUUUGGUGGCCCAUCUAAUCACGACACCUUUAGAGAAAGGGACUCCACGACUCCUUACGAACGGAUCCUACUUCAGCUUCCGCUGCACGAUCAUACGAAUCUGAUUCUUCGAAUUUUAAACUGCGCACGCCAGAGAAGGAGUAAUUGGCCAGAGAAUGCUCCACGCAGGCCGCAAGCUUUAUUAUUCCUGUCCUUUGUCCUGGGGCCUCUCAACGGAUCGCGUCGCCCGAGGGUACGCAGUCAGGAUAAUUUCCCAAAAAUGUGUGAAGAUAGCAGGUCAAUUAUUCGUUAUAUAGUUCUCUACGCCGUUCUGCGCCACUAUAGAGGUGAUAAGACACAAUAUGUGUGGAGGGAGACUUGUCCCUUACAGUUUUUCUAUCGCGGCUGUGGGAUAGAGGCGGUCUUCCUUCGCUCCGCUUUUCAUUGGGGAACUGAUUGCACCGGUCAGACAAUUGCAUUGCAUUUAGACGACGACAGUCAGGCUAACGGCCCACAGGUAAUGUUUCGAAACGUGGAAUCCGGAACUUUUGGUCCCGCCCUCGCUAAGCAACUUCUCUGGCCUCUUGAAGUUUCUUUGUGCCUCCUUCAACCUGAGCCAACUUUAGCAGUGUUUAUAAGAACUGUGGGCUACAAUUAUACGAGCACAGCGGUUUCAAAUCGUACCCUAAACAUUGAUAUUCAGUGGACCGUGCGAUUCGAUAGAGUGGCAAGCAUCCAUACACGCGUUGUAUUCUUAGAGAAGACCGAAGUGUUUGCAUUACUCCCACCUAGAGGAGCCGGCUUCUCUACUCAAACCCUUCAGGCGCUUUCCGGACUACUGGCGUUCAACCCGAAUCUGGUUAUUACUUCUAAUACUUAUGGUAGGGGAUUACCCCUCGAGAGGGCCACUAAACUGCCUUGCAUGUUACCCUUCUGCUUACAUUUCCGAGCACAUGCCCGUGCGGUUCUCCCAGGCCUUGAUCGAGCUAGUCGGUUAACCAUUAAGAGUUGGUGUGUCACGAGCUGGCUGCGUACCUCCUACUAUGCGGAAUCGCGUGGCCCUAUUAGCAAGACCCGGCCCAACAUUCUAGUGAGUCGACGCGAGACUUUUGAAGAGAGAAUGAACUACGAAAGUCAUAGGGCCUCCUGUGCAAGGCAACACACAACUAGAGCUUGGUCUUUAGGUUUGGUGUGGCCAGCCGAAGACGCCUGUCAGGGCUCCGGAGUUCUCCACAGCACCCACACGAUUGUAGGGAUUAUAAGAGUCCAUUUUAACAGGGCGAUCGCACUAUUGUCGCGCCAUCUAACGAGGCAAGGGUGCAGCAUUGCUGGUAUAGUGUGGAUGGGGCUUCGCCGAGCUAGAUUAGUUCACCAUAGGCCCCCGCAUGGACCGAAUUCUCCUACGGUUCACAAACAGCCAGGUGCCCAGGCAUGGUCAGGGCGGAACACAUUCAGUCGACCUAUUACAUCGUCCGGGGAUUUACUGUCACAGGGCUGGCAUGUCGUGUUGCACGCGUGCCGGCUGGGUGACCGUUUAGGCCUGCCAAGUUACAGACAACAUCCAUGCCUGGAAGUUCUACGAAUUCCCGCUCCGUUAUGUGUCUUUCUCUGGCGGUCGGAAUUAGAUGCAUCGAAACUAGGGCAUUACUGCCUCUGCCCGGGUCAGAUUUUGCUAAGGCGAGUUACCGCGACCGGAGCUGCCCCCUGCCAACUGAAGGGCGUGGCCAUGGAAUCUUCAAGCACCUGCCCUCUCGAGACCUUUGUAGCGAGCUCAAUAUUAUGCCGGUUUGACCACCGGCUCUCGCCCACGUGCUCUUCUCCUCGCUUUACGAGCCCCAACGUUGGGACUCGUAGCCAAGACAUUUUCCGUCUACCGCGCUACCGCACGCAAGCACGUAUGUUUUACAGAGUGGACAGAUCGACCCGUAUAAAGUCGAGCCCAGUUUGGCCUAGGGUAUUCGUCAACAGUCUAAGGCAGAGGAUGUGCCUCGGUCUUCCUAUACCAUUGAUUAAGUUAUCGUCAAUGUCCAACUUUUGGCGCUUUGGCCUACUUGACUUGGUCAUUGAUCACGGAUGCCUGCGAUUCAGAUGUGCUGAUCGUAACAAUUAA
"
-- MAMAPRTEINSTRING
